version: "3.3"

services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: tech-admin
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            - db
        build: .
        ports:
            - "8080:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DEBUG: "true"
        volumes:
            - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./src/themes/:/var/www/html/wp-content/themes/:cached
            - ./src/uploads/:/var/www/html/wp-content/uploads/:cached

volumes:
    db_data:
